language: go
go:
  - 1.7
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
script:
  - go test -v $(go list -e ./... | grep -v vendor)
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" -arch="amd64" -os="windows linux darwin" github.com/popstas/pixel-server/app
  - ghr --username popstas --token $GITHUB_TOKEN --replace --prerelease --debug latest dist/